spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.56.103:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: fmcs
    password: fmcs

      ##网易系(126/163/yeah)邮箱配置
  mail:
      host: smtp.163.com #发送邮件服务器
      username: sha19941220@163.com #发送邮件的邮箱地址(从哪里发送的)
      password: UXMVFYKVKRYODAIW #客户端授权码，不是邮箱密码,网易的是自己设置的
      properties.mail.smtp.port: 994 #465或者994
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8


server:
  port: 9090

#打印sql
logging:
  level:
    com.hook: debug

#mybatis配置

mybatis:
  mapper-locations: classpath:/generator/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
